# Build point array given

In [ ]:
! pip install haversine
! pip install vincenty

In [19]:
from haversine import *
import pandas as pd

In [3]:
# Bounding box over london
bottom_left = (51.251246, -0.621715)
top_right = (51.715616, 0.369802)

top_left = (51.715616, -0.621715)
bottom_right = (51.251246, 0.369802)

1. chose n
2. divide length by n to get distance r
3. find point r south from top left
4. find point r south from top right
5. get distance between 2 points. Thi

Key points:
Points must be evenly spaced creating circles with a chosen diameter
Number of points spaced along the vertical will be consistent anywhere you move horizontally
However, number points spaced along the horizonal will chance as you move vertically

1. Choose diameter of circle
2. Divide vertical length by diameter to work out number of rows
3. Now iterate through rows 
for i in range(len(rows)):
  i. Get row start point and row end point moving right to left by moving r*diameter down from top left and top right
  ii. calcualte horizontal distance to right line
  iii. Divide by diameter of circle to get circles on the row
  iv. If there's a remainder, divide by 2 and shift along to the right
  v. create calcuated number of circles on the row

In [34]:
# 1. Choose diameter of circle in km
d = 0.1

# 2. Divide vertical length by diameter to work out number of rows
length = haversine(top_right, bottom_right)
num_rows = int(length // d)
print(num_rows)

# 3. iterate through rows
points = []
for r in range(num_rows):
  # i. Get row start point and row end point moving right to left by moving r*diameter down from top left and top right
  row_start_point = inverse_haversine(top_left, r * d, Direction.SOUTH)
  row_end_point = inverse_haversine(top_right, r * d, Direction.SOUTH)
  
  # ii. calcualte horizontal distance to right line
  row_width = haversine(row_start_point, row_end_point)
  
  #iii. Divide by diameter of circle to get circles on the row
  
  number_points_on_row = int(row_width // d)
  
  # iv. If there's a remainder, divide by 2 and shift along to the right
  shift = ((row_width / d) % 1) / 2
  row_start_point = inverse_haversine(row_start_point, shift, Direction.EAST)
  # v. create calcuated number of circles on the row
  points_in_row_list = []
  for i in range(number_points_on_row):
    points_in_row_list.append(inverse_haversine(row_start_point, i*d, Direction.EAST))
  
  points = points + points_in_row_list
  
print("done")

5
[(51.71561584571445, -0.6156855768501859), (51.715526427062095, -0.47053228306070766), (51.7152581723861, -0.3253801372653272), (51.714811085529696, -0.18023028739235467), (51.714185172897885, -0.03508388123853474), (51.71338044345708, 0.11005793359671387)]
[(51.71561584571445, -0.6156855768501859), (51.715526427062095, -0.47053228306070766), (51.7152581723861, -0.3253801372653272), (51.714811085529696, -0.18023028739235467), (51.714185172897885, -0.03508388123853474), (51.71338044345708, 0.11005793359671387), (51.62568380477187, -0.6155992062069833), (51.6255946741446, -0.47073380981854496), (51.62532728353298, -0.32586955177831484), (51.624881636747425, -0.18100757036961385), (51.62425774013833, -0.03614900374599711), (51.623455602595634, 0.1087050101336057)]
[(51.71561584571445, -0.6156855768501859), (51.715526427062095, -0.47053228306070766), (51.7152581723861, -0.3253801372653272), (51.714811085529696, -0.18023028739235467), (51.714185172897885, -0.03508388123853474), (51.71338044345708, 0.11005793359671387), (51.62568380477187, -0.6155992062069833), (51.6255946741446, -0.47073380981854496), (51.62532728353298, -0.32586955177831484), (51.624881636747425, -0.18100757036961385), (51.62425774013833, -0.03614900374599711), (51.623455602595634, 0.1087050101336057), (51.53575176378451, -0.6155132841454204), (51.535662920042775, -0.47093428989921327), (51.53539639007692, -0.32635642444897117), (51.5349521776649, -0.18178081652665853), (51.53433028910303, -0.037208594736247054), (51.533530733205545, 0.10735911251025859)]
[(51.71561584571445, -0.6156855768501859), (51.715526427062095, -0.47053228306070766), (51.7152581723861, -0.3253801372653272), (51.714811085529696, -0.18023028739235467), (51.714185172897885, -0.03508388123853474), (51.71338044345708, 0.11005793359671387), (51.62568380477187, -0.6155992062069833), (51.6255946741446, -0.47073380981854496), (51.62532728353298, -0.32586955177831484), (51.624881636747425, -0.18100757036961385), (51.62425774013833, -0.03614900374599711), (51.623455602595634, 0.1087050101336057), (51.53575176378451, -0.6155132841454204), (51.535662920042775, -0.47093428989921327), (51.53539639007692, -0.32635642444897117), (51.5349521776649, -0.18178081652665853), (51.53433028910303, -0.037208594736247054), (51.533530733205545, 0.10735911251025859), (51.44581972275324, -0.6154278075880569), (51.445731164765604, -0.47113373048324914), (51.44546549205137, -0.32684077271470435), (51.44502270835635, -0.18255005355555842), (51.444402819923305, -0.03826269215270032), (51.443605835491496, 0.10602019253633033)]
[(51.71561584571445, -0.6156855768501859), (51.715526427062095, -0.47053228306070766), (51.7152581723861, -0.3253801372653272), (51.714811085529696, -0.18023028739235467), (51.714185172897885, -0.03508388123853474), (51.71338044345708, 0.11005793359671387), (51.62568380477187, -0.6155992062069833), (51.6255946741446, -0.47073380981854496), (51.62532728353298, -0.32586955177831484), (51.624881636747425, -0.18100757036961385), (51.62425774013833, -0.03614900374599711), (51.623455602595634, 0.1087050101336057), (51.53575176378451, -0.6155132841454204), (51.535662920042775, -0.47093428989921327), (51.53539639007692, -0.32635642444897117), (51.5349521776649, -0.18178081652665853), (51.53433028910303, -0.037208594736247054), (51.533530733205545, 0.10735911251025859), (51.44581972275324, -0.6154278075880569), (51.445731164765604, -0.47113373048324914), (51.44546549205137, -0.32684077271470435), (51.44502270835635, -0.18255005355555842), (51.444402819923305, -0.03826269215270032), (51.443605835491496, 0.10602019253633033), (51.355887681678894, -0.615342773486314), (51.35579940832203, -0.4713321386838487), (51.355534589489515, -0.32732261384939615), (51.355093228895335, -0.18331530888870104), (51.35447533272923, -0.03931133358298146), (51.35368090965625, 0.10468820247331453)]

In [35]:
latitude = []
longitide = []

for point in points:
  latitude.append(point[0])
  longitide.append(point[1])
  
  
points_df = pd.DataFrame({'Latitude': latitude, 'Longitude' : longitide, 'Magnitude' : pd.Series([1 for i in range(len(points))])})
points_df

     Latitude  Longitude  Magnitude
0   51.715616  -0.615686          1
1   51.715526  -0.470532          1
2   51.715258  -0.325380          1
3   51.714811  -0.180230          1
4   51.714185  -0.035084          1
5   51.713380   0.110058          1
6   51.625684  -0.615599          1
7   51.625595  -0.470734          1
8   51.625327  -0.325870          1
9   51.624882  -0.181008          1
10  51.624258  -0.036149          1
11  51.623456   0.108705          1
12  51.535752  -0.615513          1
13  51.535663  -0.470934          1
14  51.535396  -0.326356          1
15  51.534952  -0.181781          1
16  51.534330  -0.037209          1
17  51.533531   0.107359          1
18  51.445820  -0.615428          1
19  51.445731  -0.471134          1
20  51.445465  -0.326841          1
21  51.445023  -0.182550          1
22  51.444403  -0.038263          1
23  51.443606   0.106020          1
24  51.355888  -0.615343          1
25  51.355799  -0.471332          1
26  51.355535  -0.327323          1
27  51.355093  -0.183315          1
28  51.354475  -0.039311          1
29  51.353681   0.104688          1

In [38]:
points_df.to_csv('/Users/liamd/Documents/AI Bench/ASDI_competition/ASDI-Hackathon/Spikes/Dash/data/point_array_10.csv')

In [39]:
points_df = pd.read_csv('/Users/liamd/Documents/AI Bench/ASDI_competition/ASDI-Hackathon/Spikes/Dash/data/point_array_10.csv', index_col=0)
points_df

     Latitude  Longitude  Magnitude
0   51.715616  -0.615686          1
1   51.715526  -0.470532          1
2   51.715258  -0.325380          1
3   51.714811  -0.180230          1
4   51.714185  -0.035084          1
5   51.713380   0.110058          1
6   51.625684  -0.615599          1
7   51.625595  -0.470734          1
8   51.625327  -0.325870          1
9   51.624882  -0.181008          1
10  51.624258  -0.036149          1
11  51.623456   0.108705          1
12  51.535752  -0.615513          1
13  51.535663  -0.470934          1
14  51.535396  -0.326356          1
15  51.534952  -0.181781          1
16  51.534330  -0.037209          1
17  51.533531   0.107359          1
18  51.445820  -0.615428          1
19  51.445731  -0.471134          1
20  51.445465  -0.326841          1
21  51.445023  -0.182550          1
22  51.444403  -0.038263          1
23  51.443606   0.106020          1
24  51.355888  -0.615343          1
25  51.355799  -0.471332          1
26  51.355535  -0.327323          1
27  51.355093  -0.183315          1
28  51.354475  -0.039311          1
29  51.353681   0.104688          1